apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: hello-world/python-hello-world
  newName: btanusi8/interview-prep
  newTag: cf1b4f6b33dc46da8cf3be752e234131ca93802e
