apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: hello-world/python-hello-world
  newName: btanusi8/interview-prep
  newTag: 70ac30be941e73dc221db0b443de2fd2006c6da9
