apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: hello-world/python-hello-world
  newName: btanusi8/interview-prep
  newTag: acfb1f27e169ad8c5d4dff92ab47dcbe4b41e891
